### ISSUE TITLE
Adding a form field to the admin product page

### ISSUE THREAD

**Issue by Bossman1337** [Invertus/ps-training#1]
Can you add a form field to the admin product page, then save on submit?

I have created a form field and loaded from my repository when the page loads, but cant save it as the Tools::GetValue() won't work. Is this because the form is submitted by Ajax as FormData?

**Comment by sarjon** [comment]
hey @Bossman1337 , what do you mean exactly?

There is a hook `displayAdminProductsExtra` which allows you adding custom fields to Product page in Back Office.

**Comment by Bossman1337** [comment]
I'm working on a Module now, it's not as simple as using that hook. I've got the forms added etc, just trying to get Doctrine db working now...

**Comment by sarjon** [comment]
@Bossman1337 sorry, but I don't understand your question. :confused: 

This module is not mean to solve specific issue, it's just an example (which may not even be complete, but everyone can contribute) of what developers can do in PrestaShop 1.7.5 and above modules. 

I'm closing this issue as your questions are unclear and out of scope.
